service:
  name: certificator

provider: 
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false # to disable function versioning

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::*"
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource:
            - '*'


  environment:
    CERTIFICATES_TABLE: ${self:custom.${self:provider.stage}.database.users_certificate.name}
    CERTIFICATE_BUCKET: ${self:custom.${self:provider.stage}.buckets.users_certificate.name}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
custom:
  # serverless-offline:
  #   httpPort: 4000
  s3:
    host: localhost
    directory: /tmp
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8080
      inMemory: true
      migrate: true
  dev:
    buckets:
      users_certificate:
        name: users-certificate-${self:provider.stage}
    database:
      users_certificate:
        name: users-certificate-${self:provider.stage}

functions:
  generateCertificate:
    handler: src/functions/generateCertificate.handler
    events:
      - http:
          path: /certificate
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:${self:provider.stage}:*:table/${self:custom.${self:provider.stage}.database.users_certificate.name}
  verifyCertificate:
    handler: src/functions/verifyCertificate.handler
    events:
      - http:
          path: /certificate/{id}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - arn:aws:dynamodb:${self:provider.stage}:*:table/${self:custom.${self:provider.stage}.database.users_certificate.name}
resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.${self:provider.stage}.database.users_certificate.name}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    bucketCertificateUsers:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.${self:provider.stage}.buckets.users_certificate.name}
