service:
  name: certificator

provider: 
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false # to disable function cache

plugins:
  - serverless-offline
  - serverless-webpack


custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: /hello
          method: GET
          cors: true